export const reportData = {
	meta: {
		title: "2025-2026年越南电动两轮车市场",
		subtitle: "越南电动两轮车市场调研",
		date: "2025年1月",
		author: "翁树军、杨扬",
	},
	marketOverview: {
		totalHolding: "8,000万",
		annualProduction: "350万",
		dominantPlayer: "Honda (占70%以上份额)",
		status: "从燃油车向电动车快速切换的早中期阶段",
		banPusher: "VinFast (温纳集团) 是禁摩令的主要推动者",
		clusters: [
			{
				name: "兴安省 (Hung Yen)",
				desc: "配套厂家最密集，租金 ~$3.5/㎡/月",
				brands: [
					"台铃 (Tailg)",
					"Osakar",
					"JVC",
					"Victoria",
					"Detech",
					"同明 (Dong Minh)",
					"赛鸽 (Saige)",
					"Souda",
				],
				suppliers: ["精锐 (Jingrui)", "昊旺 (Hao Wang)", "线束厂", "烤漆厂"],
			},
			{
				name: "北宁/北江 (Bac Ninh/Giang)",
				desc: "中国头部品牌基地，租金 ~$4.5/㎡/月",
				brands: ["雅迪 (Yadea)", "爱玛 (Aima)", "DV Motor", "SMB"],
			},
		],
	},
	competition: {
		note: "注：续航里程多为厂家标称工况数据；铅酸车型普遍限速在50km/h以下（免驾照合规）。",
		tiers: [
			{
				name: "第一梯队：绝对统领（不计成本）",
				brands: [
					{
						name: "VinFast",
						logo: "/logos/Vinfast_logo.png",
						yield2025: "40万辆",
						plan2026: "150万辆",
						desc: "单车最高亏损 5000 RMB。垄断级生态链与断档级福利，民族认同感极高。依靠政策话语权实施降维打击。",
						models: [
							{
								name: "Evo 200",
								price: "22,000,000 VND",
								rmbPrice: "5,845",
								spec: "LFP 3.5kWh / 1500W",
								speedRange: "70 km/h / 203 km",
								image: "/model_images/Vinfast/Evo 200.webp",
								note: "销量王。价格屠夫，两轮滴滴首选。",
							},
							{
								name: "Feliz S",
								price: "29,700,000 VND",
								rmbPrice: "7,891",
								spec: "LFP 3.5kWh / 1800W",
								speedRange: "78 km/h / 198 km",
								image: "/model_images/Vinfast/Feliz S.webp",
							},
							{
								name: "Klara S2",
								price: "35,000,000 VND",
								rmbPrice: "9,301",
								spec: "LFP 3.5kWh / 1800W",
								speedRange: "78 km/h / 194 km",
								image: "/model_images/Vinfast/Klara S2.webp",
							},
							{
								name: "Vento S",
								price: "50,000,000 VND",
								rmbPrice: "13,287",
								spec: "LFP 3.5kWh / 3000W",
								speedRange: "89 km/h / 160 km",
								image: "/model_images/Vinfast/Vento S.webp",
								note: "侧挂电机，ABS配置。",
							},
						],
					},
				],
			},
			{
				name: "第二梯队：强势竞对",
				brands: [
					{
						name: "雅迪 (Yadea)",
						logo: "/logos/Yadea_Logo.png",
						yield2025: "15万辆",
						plan2026: "30万辆",
						desc: "350亩新厂房第一期3月开业。计划逐步淘汰老化车型(特斯拉款)。",
						models: [
							{
								name: "Voltguard U50",
								price: "35,990,000 VND",
								rmbPrice: "9,562",
								spec: "72V 50Ah LFP / 1500W",
								speedRange: "63 km/h / 200 km",
								image: "/model_images/Yadea/Voltguard U50.png",
								note: "雅迪冲击高端新品。",
							},
							{
								name: "Odora S2",
								price: "16,500,000 VND",
								rmbPrice: "4,384",
								spec: "60V 22Ah 石墨烯 / 600W",
								speedRange: "46 km/h / 80 km",
								image: "/model_images/Yadea/Odora S2.png",
								note: "大龟款，走量。",
							},
							{
								name: "Orla",
								price: "20,490,000 VND",
								rmbPrice: "5,444",
								spec: "60V 22Ah 石墨烯 / 800W",
								speedRange: "48 km/h / 65 km",
								image: "/model_images/Yadea/Orla P.jpg",
								note: "复古款，走量。",
							},
							{
								name: "i8 (新133)",
								price: "12,990,000 VND",
								rmbPrice: "3,451",
								spec: "48V 22Ah 石墨烯 / 350W",
								speedRange: "35 km/h / 70 km",
								image: "/model_images/Yadea/i8.png",
								note: "入门代步。",
							},
						],
					},
				],
			},
			{
				name: "第三梯队：细分玩家与现状",
				brands: [
					{
						name: "Detech (Espero)",
						logo: "/logos/Detech_logo.png",
						yield2025: "6万辆",
						plan2026: "15万辆",
						desc: "本土老牌，渠道下沉深。",
						models: [
							{
								name: "Classic Plus",
								price: "18,500,000 VND",
								rmbPrice: "4,925",
								spec: "60V 22.3Ah 铅酸 / 1600W",
								speedRange: "50 km/h / 90 km",
								image: "/model_images/Detech/Classic Plus.webp",
								note: "旗舰特斯拉/Vespa款。",
							},
							{
								name: "Weezee",
								price: "14,200,000 VND",
								rmbPrice: "3,780",
								spec: "48V 12Ah 锂电 / 227W",
								speedRange: "25 km/h / 60 km",
								image: "/model_images/Detech/Weezee.webp",
								note: "网红款，低速电动车。",
							},
							{
								name: "XMEN CPI-1",
								price: "15,500,000 VND",
								rmbPrice: "4,127",
								spec: "60V 20/26Ah 铅酸 / 1600W",
								speedRange: "50 km/h / 90 km",
								image: "/model_images/Detech/XMEN CPI-1.webp",
								note: "战警公模。",
							},
							{
								name: "GOGO-F1 Pro",
								price: "17,500,000 VND",
								rmbPrice: "4,659",
								spec: "60V 20/26Ah 铅酸 / 1600W",
								speedRange: "50 km/h / 90 km",
								image: "/model_images/Detech/GOGO-F1 Pro.webp",
								note: "GOGO公模。",
							},
						],
					},
					{
						name: "JVC",
						logo: "/logos/Jvc_logo.png",
						yield2025: "6万辆",
						plan2026: "10万辆",
						desc: "备战开年订单，拥有大量网红款库存及JP Motor贴牌库存。",
						models: [
							{
								name: "G9 NEW",
								price: "14,490,000 VND",
								rmbPrice: "3,858",
								spec: "48V 20Ah 铅酸 / 500W",
								speedRange: "42 km/h / 96 km",
								image: "/model_images/JVC/G9 NEW.png",
								note: "网红车，主打高个女生。",
							},
							{
								name: "V2 Pro",
								price: "18,990,000 VND",
								rmbPrice: "5,056",
								spec: "60V 20Ah 铅酸 / 800W",
								speedRange: "47 km/h / 80 km",
								image: "/model_images/JVC/V2 Pro.png",
								note: "特斯拉/Vespa公模改款。",
							},
							{
								name: "Xmen F1",
								price: "15,500,000 VND",
								rmbPrice: "4,127",
								spec: "60V 20Ah 铅酸 / 800W",
								speedRange: "47 km/h / 113 km",
								image: "/model_images/JVC/Xmen F1.png",
								note: "战警公模。",
							},
							{
								name: "ZH",
								price: "22,990,000 VND",
								rmbPrice: "6,121",
								spec: "72V 20Ah 铅酸 / 1500W",
								speedRange: "43-47 km/h / 90 km",
								image: "/model_images/JVC/ZH.png",
								note: "仿SH款 (EX007)。高价低配。",
							},
						],
					},
					{
						name: "台铃 (Tailg)",
						logo: "/logos/tailg_logo.webp",
						yield2025: "5万辆",
						plan2026: "15万辆",
						desc: "受灵都(LD)套件质量问题困扰，明年重点转向 B2B 市场。",
						models: [
							{
								name: "R52",
								price: "17,990,000 VND",
								rmbPrice: "4,780",
								spec: "60V 23Ah 铅酸 / 800W",
								speedRange: "49 km/h / 60 km",
								image: "/model_images/Tailg/R52.png",
								note: "特斯拉/Vespa款。锂电升级目标。",
							},
							{
								name: "T61",
								price: "27,900,000 VND",
								rmbPrice: "7,414",
								spec: "72V 32Ah 铅酸 / 2000W",
								speedRange: "60 km/h / 70 km",
								image: "/model_images/Tailg/T61.jpg",
								note: "EX007。车重痛点，需锂电减重。",
							},
							{
								name: "X51",
								price: "14,600,000 VND",
								rmbPrice: "3,887",
								spec: "60V 20Ah 铅酸 / 800W",
								speedRange: "48 km/h / 60 km",
								image: "/model_images/Tailg/X51.png",
								note: "133升级款。",
							},
							{
								name: "GR55",
								price: "12,990,000 VND",
								rmbPrice: "3,458",
								spec: "48V 22.3Ah 铅酸 / 400W",
								speedRange: "40 km/h / 60 km",
								image: "/model_images/Tailg/GR55.jpg",
								note: "网红款，走量。",
							},
						],
					},
					{
						name: "Osakar",
						logo: "/logos/Osakar_logo.jpg",
						yield2025: "-",
						plan2026: "-",
						desc: "高端GOGO/Vespa款为主。",
						models: [
							{
								name: "NISPA VERA X",
								price: "18,500,000 VND",
								rmbPrice: "4,925",
								spec: "60V 20Ah 铅酸 / 1000W",
								speedRange: "46 km/h / 80 km",
								image: "/model_images/Osakar/NISPA VERA X.webp",
								note: "旗舰特斯拉/Vespa款。",
							},
							{
								name: "VC SUNOO",
								price: "14,500,000 VND",
								rmbPrice: "3,860",
								spec: "48V 20Ah 铅酸 / 500W",
								speedRange: "38 km/h / 60 km",
								image: "/model_images/Osakar/VC SUNOO.png",
								note: "网红款。",
							},
							{
								name: "Xmen Pro",
								price: "17,000,000 VND",
								rmbPrice: "4,526",
								spec: "60V 20Ah 铅酸 / 1000W",
								speedRange: "43 km/h / 90 km",
								image: "/model_images/Osakar/XMEN PRO.png",
								note: "战警公模。",
							},
							{
								name: "GOGO FIONA",
								price: "18,000,000 VND",
								rmbPrice: "4,792",
								spec: "60V 20Ah 铅酸 / 1000W",
								speedRange: "49 km/h / 80 km",
								image: "/model_images/Osakar/GOGO FIONA.png",
								note: "高端GOGO。",
							},
						],
					},
					{
						name: "Dibao",
						logo: "/logos/Dibao_logo.webp",
						yield2025: "-",
						plan2026: "-",
						desc: "EX007与大功率铅酸为主。",
						models: [
							{
								name: "LS 007",
								price: "27,690,000 VND",
								rmbPrice: "7,372",
								spec: "72V 22Ah 铅酸 / 2800W",
								speedRange: "54 km/h / 60-100 km",
								image: "/model_images/Dibao/LS007.png",
								note: "EX007，大功率铅酸。",
							},
							{
								name: "PANSY S3",
								price: "21,990,000 VND",
								rmbPrice: "5,855",
								spec: "60V 22Ah 铅酸 / 1350W",
								speedRange: "50 km/h / 60-90 km",
								image: "/model_images/Dibao/PANSY S3.png",
								note: "特斯拉/Vespa款。",
							},
							{
								name: "ELLA",
								price: "18,690,000 VND",
								rmbPrice: "4,976",
								spec: "60V 22Ah 铅酸 / 1400W",
								speedRange: "45 km/h / 70-90 km",
								image: "/model_images/Dibao/ELLA.png",
								note: "网红款。",
							},
							{
								name: "ROSA",
								price: "18,990,000 VND",
								rmbPrice: "5,056",
								spec: "60V 23Ah 铅酸 / 1400W",
								speedRange: "45 km/h / 80-90 km",
								image: "/model_images/Dibao/ROSA.png",
							},
						],
					},
					{
						name: "Victoria",
						logo: "/logos/Victoria_logo.jpg",
						yield2025: "3万辆",
						plan2026: "8万辆",
						desc: "油改电转型中，11月订货售罄，看好 EX008 锂电版。",
						models: [
							{
								name: "Royal",
								price: "-",
								rmbPrice: "-",
								spec: "1200W",
								speedRange: "-",
								image: "/model_images/Victoria/Royal.jpeg",
								note: "高端EX007款。",
							},
							{
								name: "Viral S2",
								price: "-",
								rmbPrice: "-",
								spec: "1000W",
								speedRange: "-",
								image: "/model_images/Victoria/Viral S2.jpg",
								note: "特斯拉/Vespa款。",
							},
						],
					},
					{
						name: "Dat Bike",
						logo: "/logos/datbike_logo.png",
						yield2025: "1.5万辆",
						plan2026: "-",
						desc: "黑马。避开同质化竞争，主打中高性能差异化。",
						models: [
							{
								name: "QUANTUM S1",
								price: "49,900,000 VND",
								rmbPrice: "13,260",
								spec: "6.4kWh 锂电 / 7000W",
								speedRange: "100 km/h / 285 km",
								image: "/model_images/Dat Bike/QUANTUM S1.jpg",
								note: "B2B标杆。",
							},
							{
								name: "QUANTUM S3",
								price: "39,900,000 VND",
								rmbPrice: "10,603",
								spec: "4.3kWh 锂电 / 6000W",
								speedRange: "90 km/h / 200 km",
								image: "/model_images/Dat Bike/QUANTUM S3.png",
							},
						],
					},
					{
						name: "DV Motor",
						logo: "/logos/dvmotor_logo.jpg",
						yield2025: "5万辆",
						plan2026: "10万辆",
						desc: "联合 Kazuki 品牌运营。",
					},
					{
						name: "DKBike",
						logo: "/logos/DK_logo.jpg",
						yield2025: "2万辆 (预计)",
						plan2026: "-",
						desc: "销量腰斩，从去年4万台跌至今年的2万台。",
					},
					{
						name: "爱玛 (Aima)",
						logo: "/logos/Powelldd_logo.webp",
						yield2025: "3,000辆",
						plan2026: "6万辆",
						desc: "基数小但目标最激进。",
					},
				],
			},
		],
	},
	segments: [
		{
			title: "学生市场",
			tags: ["存量主力", "方形大灯"],
			features: "天津款与特斯拉款为主流，方形大灯设计正流行。",
			details: [
				{ label: "设计趋势", value: "方形大灯盛行" },
				{ label: "现状", value: "雅迪拟逐步放弃特斯拉款" },
			],
		},
		{
			title: "成人/通勤市场",
			tags: ["锂电升级", "品牌驱动"],
			features: "VinFast 统治该领域，锂电池是突破口。",
			insight:
				"铅酸版增长乏力。Victoria EX007 油车款稳定，锂电化转型是必然路径。",
			strategy: "各大厂纷纷布局锂电车型。",
		},
		{
			title: "B2B / 外卖配送",
			tags: ["经济性", "高端化潜力"],
			features: "运营成本大幅优于燃油车。",
			details: [
				{ label: "爆款潜力", value: "72V 90Ah 大电池" },
				{ label: "设计需求", value: "长坐垫、大脚踏板、高续航" },
			],
			costComparison: {
				ice: "750-800 RMB/月",
				ev: "100 RMB/月",
				ratio: "1/8",
			},
		},
	],
	infrastructure: {
		supplyChain: {
			title: "供应链与制造",
			details: [
				{
					label: "昊旺 (Wu Wang)",
					value: "雅迪核心车架供应商。",
				},
				{
					label: "精锐 (Jingrui)",
					value: "极强逆向仿制能力(买VinFast样车回国仿)。",
				},
				{
					label: "灵都 (LD)",
					value: "套件商面临信任危机，质量控制是软肋。",
				},
				{ label: "成本痛点", value: "本地烤漆成本比中国贵 70-90 RMB。" },
			],
		},
		operations: {
			title: "运营环境",
			details: [
				{
					label: "登检流程",
					value: "极度复杂，虽然有套件商代办，但质量风险大。",
				},
				{
					label: "政策保护",
					value: "“以旧换新”等补贴大概率仅限本土品牌独占。",
				},
			],
		},
	},
	risks: {
		protective: {
			title: "政策风险",
			desc: "越南政府环保政策背后有 VinFast 等本土巨头游说，排他性政策明显。",
		},
		ip: {
			title: "竞争风险",
			desc: "本地组装厂日益看重口碑，纯贸易型套件商面临被清洗风险。",
		},
	},
};
